"""first migration

Revision ID: 23f0c4df5b55
Revises: 
Create Date: 2025-06-17 12:35:36.691111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23f0c4df5b55'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operators',
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('operator_username', sa.String(length=100), nullable=False),
    sa.Column('operator_password', sa.String(length=100), nullable=False),
    sa.Column('operator_first_name', sa.String(length=100), nullable=False),
    sa.Column('operator_last_name', sa.String(length=100), nullable=False),
    sa.Column('operator_is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('operator_id'),
    sa.UniqueConstraint('operator_username')
    )
    op.create_table('subscribers',
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('subscriber_first_name', sa.String(length=100), nullable=False),
    sa.Column('subscriber_last_name', sa.String(length=100), nullable=False),
    sa.Column('subscriber_phone_number', sa.String(length=20), nullable=True),
    sa.Column('subscriber_note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('subscriber_id')
    )
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscribers_subscriber_phone_number'), ['subscriber_phone_number'], unique=False)

    op.create_table('subscription_campaigns',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('campaign_year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('campaign_id')
    )
    with op.batch_alter_table('subscription_campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_campaigns_campaign_year'), ['campaign_year'], unique=False)

    op.create_table('physical_tickets',
    sa.Column('physical_ticket_id', sa.Integer(), nullable=False),
    sa.Column('physical_ticket_number', sa.Integer(), nullable=False),
    sa.Column('physical_ticket_is_available', sa.Boolean(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['subscription_campaigns.campaign_id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.operator_id'], ),
    sa.PrimaryKeyConstraint('physical_ticket_id')
    )
    with op.batch_alter_table('physical_tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_physical_tickets_physical_ticket_number'), ['physical_ticket_number'], unique=False)

    op.create_table('subscriptions',
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('subscription_is_paid', sa.Boolean(), nullable=False),
    sa.Column('subscription_payment_method', sa.String(length=100), nullable=True),
    sa.Column('subscription_assigned_at', sa.DateTime(), nullable=True),
    sa.Column('subscription_note', sa.Text(), nullable=True),
    sa.Column('physical_ticket_id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['subscription_campaigns.campaign_id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.operator_id'], ),
    sa.ForeignKeyConstraint(['physical_ticket_id'], ['physical_tickets.physical_ticket_id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.subscriber_id'], ),
    sa.PrimaryKeyConstraint('subscription_id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_subscriber_id'), ['subscriber_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_subscriber_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_campaign_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('physical_tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_physical_tickets_physical_ticket_number'))

    op.drop_table('physical_tickets')
    with op.batch_alter_table('subscription_campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_campaigns_campaign_year'))

    op.drop_table('subscription_campaigns')
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscribers_subscriber_phone_number'))

    op.drop_table('subscribers')
    op.drop_table('operators')
    # ### end Alembic commands ###
