"""Add unique constrains to pampaign_year

Revision ID: 83a2b074adb4
Revises: 23f0c4df5b55
Create Date: 2025-06-17 19:18:17.650761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83a2b074adb4'
down_revision = '23f0c4df5b55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_campaigns_campaign_year'))
        batch_op.create_index(batch_op.f('ix_subscription_campaigns_campaign_year'), ['campaign_year'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_campaigns_campaign_year'))
        batch_op.create_index(batch_op.f('ix_subscription_campaigns_campaign_year'), ['campaign_year'], unique=False)

    # ### end Alembic commands ###
