"""aggiunto campo assigned_to_operator_id per assegnare i biglietti

Revision ID: b89b2c176967
Revises: 83a2b074adb4
Create Date: 2025-06-23 19:08:12.805692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b89b2c176967'
down_revision = '83a2b074adb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('physical_tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to_operator_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'operators', ['assigned_to_operator_id'], ['operator_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('physical_tickets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assigned_to_operator_id')

    # ### end Alembic commands ###
